name:                earnest
version:             0.1.0.0
github:              "github.com/y-usuzumi/earnest"
license:             BSD3
author:              "Yukio Usuzumi"
maintainer:          "anohigisavay@gmail.com"
copyright:           "2018 Yukio Usuzumi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/earnest#readme>

dependencies:
- aeson
- async
- base >= 4.7 && < 5
- bytestring
- containers
- exceptions
- fgl == 5.6.0.0
- hashable
- hashing
- lens >= 4.17
- monad-control
- mtl
- streamly == 0.4.1
- tasty
- tasty-hunit
- template-haskell
- text
- unix
- unliftio-core
- unliftio
- unordered-containers
- webdriver
- wreq

default-extensions:
- DeriveAnyClass
- DeriveFunctor
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GADTs
- OverloadedStrings
- QuasiQuotes
- PartialTypeSignatures
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies

ghc-options:
- -Werror
- -fwarn-incomplete-uni-patterns
- -fwarn-missing-methods
- -fwarn-missing-fields

library:
  source-dirs: src

executables:
  earnest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - earnest

tests:
  earnest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - earnest
