name:                earnest
version:             0.1.0.0
github:              "github.com/y-usuzumi/earnest"
license:             BSD3
author:              "Yukio Usuzumi"
maintainer:          "anohigisavay@gmail.com"
copyright:           "2018 Yukio Usuzumi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/earnest#readme>

dependencies:
- async
- base >= 4.7 && < 5
- containers
- exceptions
- hashable
- monad-control
- mtl
- tasty
- tasty-hunit
- unliftio-core
- unliftio
- unordered-containers
- webdriver

default-extensions:
- DeriveFunctor
- DeriveGeneric
- OverloadedStrings
- RankNTypes
- RecordWildCards
- TypeFamilies

library:
  source-dirs: src

executables:
  earnest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - earnest

tests:
  earnest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - earnest
