library:
  source-dirs: src
tests:
  earnest-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ListLike
    - earnest
copyright: 2018 Yukio Usuzumi
maintainer: anohigisavay@gmail.com
ghc-options:
- -Werror
- -fwarn-missing-methods
- -fwarn-missing-fields
dependencies:
- aeson
- async
- base >= 4.7 && < 5
- bytestring
- containers
- data-default
- exceptions
- fgl == 5.6.0.0
- hasbolt
- hashable
- hashing
- interpolate
- lens >= 4.17
- monad-control
- mtl
- optparse-applicative
- streamly == 0.4.1
- tasty
- tasty-hunit
- template-haskell
- text
- unix
- unliftio-core
- unliftio
- unordered-containers
- uuid
- webdriver
- wreq
- yaml
default-extensions:
- ConstraintKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GADTs
- ImplicitParams
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- QuasiQuotes
- PartialTypeSignatures
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
name: earnest
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Yukio Usuzumi
github: github.com/y-usuzumi/earnest
license: BSD3
executables:
  earnest-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - earnest
description: Please see the README on GitHub at <https://github.com/githubuser/earnest#readme>
