neo4j:
  username: "neo4j"
  password: "neo4j"
  host: "localhost"
  port: "7687"

aex:
  username: "<username>"
  password: "<password>"

aexapi:
  uid: "<uid>"
  key: "<key>"
  skey: "<skey>"

gatehub:
  username: "<username>"
  password: "<password>"

bourses: []
