bourses:  # You can add multiple entries for each bourse type
- type: aex
  username: <username>
  password: <password>
- type: aexapi
  uid: <uid>
  key: <key>
  skey: <skey>
- type: gatehub
  username: <username>
  password: <password>
